### ISSUE TITLE
Query Mask and Transformer Calculation Inconsistencies

### ISSUE THREAD

**Issue by TYEclipse** [LIUYUANWEI98/IPMT#7]
Hello @LIUYUANWEI98，
你好@LIUYUANWEI98，

First of all, I would like to thank you for the excellent work you have done on this project. It is truly impressive and has been of great help to many people, including myself. I have come across a couple of issues that I would like to discuss, and I would greatly appreciate your advice on how to address them.
首先，我要感谢您在IPMT所做的出色工作。 它确实令人印象深刻，对包括我在内的许多人都有很大帮助。 我遇到了几个我想讨论的问题，非常感谢您就如何解决这些问题提出建议。

Issue 1: Label Leakage Problem with 'y'
问题 1：用“y”标记泄漏问题

https://github.com/LIUYUANWEI98/IPMT/blob/d887858a71f51b020acbdb5620165d7ce6715c34/model/IPMTnetwork.py#L171

It appears that the query mask 'y' used in the few-shot semantic segmentation task might have a label leakage problem. Specifically, the mask of the query should be unknown to the model and only be utilized for loss calculation. However, upon examining the code, it seems that the mask information might be inadvertently incorporated into the model training. I am not certain if this was intended or not, but I believe it could lead to an incorrect evaluation of the model's performance.
似乎在小样本语义分割任务中使用的查询掩码“y”可能存在标签泄漏问题。 具体来说，查询掩码对于模型来说应该是未知的，并且只用于损失计算。 但是，在检查代码时，似乎掩码信息可能会无意中包含到模型训练中。 我不确定这是否有意为之，但我相信这可能会导致对模型性能的错误评估。

Issue 2: Inconsistencies in Transformer Calculations
Transformer计算中的不一致

While examining the transformer implementation, I noticed that some calculations seem to be inconsistent with the ones described in the original paper. I understand that there could be valid reasons for deviating from the paper's implementation, but I would like to know if these inconsistencies are deliberate or accidental. If the latter, it might be helpful to update the code to better align with the paper's methodology.
在检查转换器实现时，我注意到一些计算似乎与原始论文中描述的不一致。 我知道偏离论文的实施可能有正当理由，但我想知道这些不一致是故意的还是偶然的。 如果是后者，更新代码以更好地与本文的方法保持一致可能会有所帮助。

I hope you find these observations helpful, and I would be grateful for any insights or guidance you can provide. Thank you once again for your incredible work and dedication to this project. Looking forward to your response.
我希望这些观察对您有所帮助，如果您能提供任何见解或指导，我将不胜感激。 再次感谢您为这个项目所做的出色工作和奉献。 期待你的回复。

Best regards,
此致，

TYEclipse

**Comment by TYEclipse** [comment]
When looking into the implementation details for question 1, I observed that the querymask is set as the input_padding_mask of the MSDeformAttn module. In the current implementation, the ignored area (mask pixel=255) is set to 0 in the value, which effectively ignores edge information of the segmented area.

This might lead to a label leakage problem, as the ignored area contains valuable edge information that could impact the overall performance of the model. I would like to discuss whether this is indeed an issue and if there are any possible solutions or workarounds to address it.

**Comment by Sam1224** [comment]
Hi, @TYEclipse. Do you have any update on this issue? I tried to follow CyCTR to obtain the real padded pixels (obtained by augmentation techniques), instead of query foreground objects edges (as you worried), and the trained models do not behave well.
